version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:5000

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/roundtables
      - NODE_ENV=production
      - PORT=5000
      - JWT_SECRET=your-super-secure-jwt-secret-minimum-32-characters-long
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USER=your-email@gmail.com
      - SMTP_PASSWORD=your-app-password
      - FROM_EMAIL=noreply@makaitalia.com
      - FRONTEND_URL=http://localhost:3000
      - COORDINATOR_EMAILS=training@makaitalia.com,alessia@makaitalia.com
    depends_on:
      - db
    volumes:
      - ./backend:/app
    command: sh -c "npx prisma db push && npx prisma generate && npm start"

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=roundtables
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: